name: sync to gitee
on:
  - push
  - pull_request
jobs:
  sync:
    name: sync
    uses: Yikun/hub-mirror-action@master
    with:
      src: github/WumaCoder
      dst: gitee/WumaCoder
      dst_key: ${{ secrets.GITEE_KEY }}
      white_list: "viedo-search"
